all:
	@./generate 1 10
	@./generate 1 20
	@./generate 1 30
	@./generate 1 40

	@./generate 4 10
	@./generate 4 20
	@./generate 4 30
	@./generate 4 40

	@./generate 8 10
	@./generate 8 20
	@./generate 8 30
	@./generate 8 40

clean:
	rm -f *_*_*.json *_*.tgffopt *.tgff *.eps *.vcg

.PHONY: all clean
